### ISSUE TITLE
"Block #10 To #19 (Total of 29 Blocks)" should be list of transaction from, to, and total

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/explorer#14]
![screenshot 2018-12-20 14 53 07](https://user-images.githubusercontent.com/5106444/50262780-0693c180-0467-11e9-9239-272396982feb.png)

For example, it should say "Transactions #10 To #19 (Total of 29 Transactions)"

**Comment by Kapilbindal1** [comment]
We doesn't have transaction count. Passed the message to Andre.
We're showing now Transactions of Blocks #10 and #19
